import { IStaticReferenceCatalogMetadata } from '../../interfaces/i-reference-catalog';

export const CITIZENSHIP_CATALOG = {
  metadata: {
    sources: [
      'https://stat.gov.pl/obszary-tematyczne/ludnosc/migracje-zagraniczne-ludnosci/wykazy-krajow-urodzenia-wyjazdu-przyjazdu-obywatelstwa,9,1.html',
    ],
    verifiedAt: '2026-07-25',
    catalogVersion: '1.0.0',
  } satisfies IStaticReferenceCatalogMetadata,
  values: [
    'Polska', 'Afganistan', 'Albania', 'Algieria',
    'Andora', 'Angola', 'Antigua i Barbuda', 'Arabia Saudyjska',
    'Argentyna', 'Armenia', 'Aruba', 'Australia',
    'Austria', 'Azerbejdżan', 'Bahamy', 'Bahrajn',
    'Bangladesz', 'Barbados', 'Belgia', 'Belize',
    'Benin', 'Bhutan', 'Białoruś', 'Boliwia',
    'Bośnia i Hercegowina', 'Botswana', 'Brazylia', 'Brunei',
    'Bułgaria', 'Burkina Faso', 'Burundi', 'Chile',
    'Chiny', 'Chorwacja', 'Curaçao', 'Cypr',
    'Czad', 'Czarnogóra', 'Czechy', 'Dania',
    'Demokratyczna Republika Konga', 'Dominika', 'Dominikana', 'Dżibuti',
    'Egipt', 'Ekwador', 'Erytrea', 'Estonia',
    'Eswatini (Suasi)', 'Etiopia', 'Fidżi', 'Filipiny',
    'Finlandia', 'Francja', 'Gabon', 'Gambia',
    'Ghana', 'Grecja', 'Grenada', 'Gruzja',
    'Gujana', 'Gwatemala', 'Gwinea', 'Gwinea Bissau',
    'Gwinea Równikowa', 'Haiti', 'Hiszpania', 'Holandia',
    'Honduras', 'Indie', 'Indonezja', 'Irak',
    'Iran', 'Irlandia', 'Islandia', 'Izrael',
    'Jamajka', 'Japonia', 'Jemen', 'Jersey',
    'Jordania', 'Kambodża', 'Kamerun', 'Kanada',
    'Katar', 'Kazachstan', 'Kenia', 'Kirgistan',
    'Kiribati', 'Kolumbia', 'Komory', 'Kongo',
    'Korea Południowa', 'Korea Północna', 'Kosowo', 'Kostaryka',
    'Kuba', 'Kuwejt', 'Laos', 'Lesotho',
    'Liban', 'Liberia', 'Libia', 'Liechtenstein',
    'Litwa', 'Luksemburg', 'Łotwa', 'Macedonia Północna',
    'Madagaskar', 'Malawi', 'Malediwy', 'Malezja',
    'Mali', 'Malta', 'Maroko', 'Mauretania',
    'Mauritius', 'Meksyk', 'Mikronezja', 'Mjanma (Birma)',
    'Mołdawia', 'Monako', 'Mongolia', 'Mozambik',
    'Namibia', 'Nauru', 'Nepal', 'Niemcy',
    'Niger', 'Nigeria', 'Nikaragua', 'Norwegia',
    'Nowa Zelandia', 'Oman', 'Pakistan', 'Palau',
    'Palestyna', 'Panama', 'Papua-Nowa Gwinea', 'Paragwaj',
    'Peru', 'Portugalia', 'Republika Południowej Afryki',
    'Republika Środkowoafrykańska', 'Republika Zielonego Przylądka',
    'Rosja', 'Rumunia', 'Rwanda', 'Sahara Zachodnia',
    'Saint Kitts i Nevis', 'Saint Lucia', 'Saint Vincent i Grenadyny',
    'Salwador', 'Samoa', 'San Marino', 'Senegal',
    'Serbia', 'Seszele', 'Sierra Leone', 'Singapur',
    'Sint Maarten', 'Słowacja', 'Słowenia', 'Somalia',
    'Sri Lanka', 'Stany Zjednoczone', 'Sudan', 'Sudan Południowy',
    'Surinam', 'Syria', 'Szwajcaria', 'Szwecja',
    'Tadżykistan', 'Tajlandia', 'Tajwan', 'Tanzania',
    'Timor Wschodni', 'Togo', 'Tonga', 'Trynidad i Tobago',
    'Tunezja', 'Turcja', 'Turkmenistan', 'Tuvalu',
    'Uganda', 'Ukraina', 'Urugwaj', 'Uzbekistan',
    'Vanuatu', 'Watykan', 'Wenezuela', 'Węgry',
    'Wielka Brytania', 'Wietnam', 'Włochy',
    'Wybrzeże Kości Słoniowej', 'Wyspa Man', 'Wyspy Marshalla',
    'Wyspy Salomona', 'Wyspy Świętego Tomasza i Książęca',
    'Zambia', 'Zimbabwe', 'Zjednoczone Emiraty Arabskie',
    'Bezpaństwowiec', 'Kraj nieustalony',
  ],
} as const;
