export const QUESTIONNAIRE_PDF_COPY = {
  title: "Kwestionariusz współpracownika",
  sections: {
    personal: "Dane osobowe",
    registeredAddress: "Adres zameldowania",
    correspondenceAddress: "Adres korespondencyjny",
    institutions: "Instytucje",
    insurance: "Ubezpieczenia i pozostałe oświadczenia",
    payment: "Płatność",
    declaration: "Oświadczenie końcowe",
  },
  signature: {
    placeAndDate: "Miejscowość i data",
    coworker: "Czytelny podpis współpracownika",
  },
  labels: {
    firstName: "Imię",
    lastName: "Nazwisko",
    maidenName: "Nazwisko rodowe",
    middleName: "Drugie imię",
    birthDate: "Data urodzenia",
    birthPlace: "Miejsce urodzenia",
    identificationBasis: "Podstawa identyfikacji",
    pesel: "PESEL",
    nip: "NIP",
    identityDocumentKind: "Rodzaj dokumentu tożsamości",
    identityDocumentNumber: "Numer dokumentu tożsamości",
    citizenship: "Obywatelstwo",
    phone: "Telefon",
    street: "Ulica",
    houseNumber: "Numer domu",
    apartmentNumber: "Numer lokalu",
    postalCode: "Kod pocztowy",
    city: "Miejscowość",
    voivodeship: "Województwo",
    county: "Powiat",
    municipality: "Gmina",
    postOffice: "Poczta",
    countryCode: "Kod kraju",
    legacyCountryName: "Historyczna nazwa kraju",
    sameAsRegistered: "Taki sam jak adres zameldowania",
    taxOfficeKind: "Rodzaj danych urzędu skarbowego",
    taxOfficeCode: "Kod urzędu skarbowego",
    taxOfficeName: "Nazwa urzędu skarbowego",
    nfzBranchKind: "Rodzaj danych oddziału NFZ",
    nfzBranchCode: "Kod oddziału NFZ",
    nfzBranchName: "Nazwa oddziału NFZ",
    otherEmployment: "Inne zatrudnienie",
    otherEmployerName: "Nazwa innego pracodawcy",
    otherEmploymentAtLeastMinimumWage: "Wynagrodzenie co najmniej minimalne",
    studentUnder26: "Uczeń lub student poniżej 26 lat",
    schoolOrUniversityName: "Nazwa szkoły lub uczelni",
    otherMandateContract: "Inna umowa zlecenia",
    otherPrincipalName: "Nazwa innego zleceniodawcy",
    otherMandateContractSocialInsurance: "Składki społeczne z innej umowy",
    subjectToCompulsorySocialInsurance: "Obowiązkowe ubezpieczenia społeczne",
    voluntarySicknessInsurance: "Dobrowolne ubezpieczenie chorobowe",
    voluntarySicknessInsuranceJoinConfirmed:
      "Potwierdzenie przystąpienia do ubezpieczenia chorobowego",
    voluntaryPensionDisabilityInsurance:
      "Dobrowolne ubezpieczenie emerytalne i rentowe",
    hasPensionOrDisabilityPensionRight: "Prawo do emerytury lub renty",
    disabilityDegree: "Stopień niepełnosprawności",
    registeredAtEmploymentOffice: "Rejestracja w urzędzie pracy",
    employmentOfficeAddress: "Adres urzędu pracy",
    bankName: "Nazwa banku",
    bankAccount: "Numer rachunku",
    statementKey: "Klucz oświadczenia",
    statementVersion: "Wersja oświadczenia",
    statementText: "Treść oświadczenia",
    questionnaireRevision: "Rewizja kwestionariusza",
    acceptedAt: "Data akceptacji",
    actorUserId: "Identyfikator akceptującego",
    source: "Źródło",
  },
  values: {
    empty: "Brak danych",
    yes: "Tak",
    no: "Nie",
    join: "Przystępuję",
    decline: "Nie przystępuję",
    pesel: "PESEL",
    identityDocument: "Dokument tożsamości",
    idCard: "Dowód osobisty",
    passport: "Paszport",
    otherDocument: "Inny dokument",
    catalog: "Wartość katalogowa",
    legacy: "Wartość historyczna",
    disabilityNone: "Brak",
    disabilityLight: "Lekki",
    disabilityModerate: "Umiarkowany",
    disabilitySevere: "Znaczny",
  },
} as const;
