export const QUESTIONNAIRE_PDF_COPY = {
  title: "[PH] Kwestionariusz współpracownika",
  sections: {
    personal: "[PH] Dane osobowe",
    registeredAddress: "[PH] Adres zameldowania",
    correspondenceAddress: "[PH] Adres korespondencyjny",
    institutions: "[PH] Instytucje",
    insurance: "[PH] Ubezpieczenia i pozostałe oświadczenia",
    payment: "[PH] Płatność",
    declaration: "[PH] Oświadczenie końcowe",
  },
  labels: {
    firstName: "[PH] Imię",
    lastName: "[PH] Nazwisko",
    maidenName: "[PH] Nazwisko rodowe",
    middleName: "[PH] Drugie imię",
    birthDate: "[PH] Data urodzenia",
    birthPlace: "[PH] Miejsce urodzenia",
    identificationBasis: "[PH] Podstawa identyfikacji",
    pesel: "[PH] PESEL",
    nip: "[PH] NIP",
    identityDocumentKind: "[PH] Rodzaj dokumentu tożsamości",
    identityDocumentNumber: "[PH] Numer dokumentu tożsamości",
    citizenship: "[PH] Obywatelstwo",
    phone: "[PH] Telefon",
    street: "[PH] Ulica",
    houseNumber: "[PH] Numer domu",
    apartmentNumber: "[PH] Numer lokalu",
    postalCode: "[PH] Kod pocztowy",
    city: "[PH] Miejscowość",
    voivodeship: "[PH] Województwo",
    county: "[PH] Powiat",
    municipality: "[PH] Gmina",
    postOffice: "[PH] Poczta",
    countryCode: "[PH] Kod kraju",
    legacyCountryName: "[PH] Historyczna nazwa kraju",
    sameAsRegistered: "[PH] Taki sam jak adres zameldowania",
    taxOfficeKind: "[PH] Rodzaj danych urzędu skarbowego",
    taxOfficeCode: "[PH] Kod urzędu skarbowego",
    taxOfficeName: "[PH] Nazwa urzędu skarbowego",
    nfzBranchKind: "[PH] Rodzaj danych oddziału NFZ",
    nfzBranchCode: "[PH] Kod oddziału NFZ",
    nfzBranchName: "[PH] Nazwa oddziału NFZ",
    otherEmployment: "[PH] Inne zatrudnienie",
    otherEmployerName: "[PH] Nazwa innego pracodawcy",
    otherEmploymentAtLeastMinimumWage:
      "[PH] Wynagrodzenie co najmniej minimalne",
    studentUnder26: "[PH] Uczeń lub student poniżej 26 lat",
    schoolOrUniversityName: "[PH] Nazwa szkoły lub uczelni",
    otherMandateContract: "[PH] Inna umowa zlecenia",
    otherPrincipalName: "[PH] Nazwa innego zleceniodawcy",
    otherMandateContractSocialInsurance: "[PH] Składki społeczne z innej umowy",
    subjectToCompulsorySocialInsurance:
      "[PH] Obowiązkowe ubezpieczenia społeczne",
    voluntarySicknessInsurance: "[PH] Dobrowolne ubezpieczenie chorobowe",
    voluntarySicknessInsuranceJoinConfirmed:
      "[PH] Potwierdzenie przystąpienia do ubezpieczenia chorobowego",
    voluntaryPensionDisabilityInsurance:
      "[PH] Dobrowolne ubezpieczenie emerytalne i rentowe",
    hasPensionOrDisabilityPensionRight: "[PH] Prawo do emerytury lub renty",
    disabilityDegree: "[PH] Stopień niepełnosprawności",
    registeredAtEmploymentOffice: "[PH] Rejestracja w urzędzie pracy",
    employmentOfficeAddress: "[PH] Adres urzędu pracy",
    bankName: "[PH] Nazwa banku",
    bankAccount: "[PH] Numer rachunku",
    statementKey: "[PH] Klucz oświadczenia",
    statementVersion: "[PH] Wersja oświadczenia",
    statementText: "[PH] Treść oświadczenia",
    questionnaireRevision: "[PH] Rewizja kwestionariusza",
    acceptedAt: "[PH] Data akceptacji",
    actorUserId: "[PH] Identyfikator akceptującego",
    source: "[PH] Źródło",
  },
  values: {
    empty: "[PH] Brak danych",
    yes: "[PH] Tak",
    no: "[PH] Nie",
    join: "[PH] Przystępuję",
    decline: "[PH] Nie przystępuję",
    pesel: "[PH] PESEL",
    identityDocument: "[PH] Dokument tożsamości",
    idCard: "[PH] Dowód osobisty",
    passport: "[PH] Paszport",
    otherDocument: "[PH] Inny dokument",
    catalog: "[PH] Wartość katalogowa",
    legacy: "[PH] Wartość historyczna",
    disabilityNone: "[PH] Brak",
    disabilityLight: "[PH] Lekki",
    disabilityModerate: "[PH] Umiarkowany",
    disabilitySevere: "[PH] Znaczny",
  },
} as const;
