export const SESSION_SINGLE_SESSION_PRODUCT_SLUG = 'single-session';
export const SESSION_PACKAGE_3_SESSIONS_PRODUCT_SLUG = 'package-3-sessions';
export const SESSION_PACKAGE_5_SESSIONS_PRODUCT_SLUG = 'package-5-sessions';
export const SESSION_SUBSCRIPTION_2_SESSIONS_MONTH_PRODUCT_SLUG =
  'subscription-2-sessions-month';
export const SESSION_SUBSCRIPTION_4_SESSIONS_MONTH_PRODUCT_SLUG =
  'subscription-4-sessions-month';

export const SESSION_ADDON_ONLINE_SESSION_PRODUCT_SLUG = 'addon-online-session';
export const SESSION_ADDON_CHARACTER_SHEET_PRODUCT_SLUG =
  'addon-character-sheet';
export const SESSION_ADDON_SESSION_ZERO_PRODUCT_SLUG = 'addon-session-zero';
export const SESSION_ADDON_NEW_CAMPAIGN_PRODUCT_SLUG = 'addon-new-campaign';
export const SESSION_ADDON_THEMATIC_PROPS_PRODUCT_SLUG =
  'addon-thematic-props';
export const SESSION_ADDON_EXTRA_HOUR_PRODUCT_SLUG = 'addon-extra-hour';
export const SESSION_ADDON_HYBRID_SERVICE_PRODUCT_SLUG =
  'addon-hybrid-service';
export const SESSION_ADDON_SCENARIO_CUSTOMIZATION_PRODUCT_SLUG =
  'addon-scenario-customization';
export const SESSION_CUSTOM_ADDITIONAL_SERVICE_PRODUCT_SLUG =
  'custom-additional-service';

export const SESSION_BASE_PRODUCT_SLUGS = [
  SESSION_SINGLE_SESSION_PRODUCT_SLUG,
  SESSION_PACKAGE_3_SESSIONS_PRODUCT_SLUG,
  SESSION_PACKAGE_5_SESSIONS_PRODUCT_SLUG,
  SESSION_SUBSCRIPTION_2_SESSIONS_MONTH_PRODUCT_SLUG,
  SESSION_SUBSCRIPTION_4_SESSIONS_MONTH_PRODUCT_SLUG,
] as const;

export const SESSION_ADDON_PRODUCT_SLUGS = [
  SESSION_ADDON_ONLINE_SESSION_PRODUCT_SLUG,
  SESSION_ADDON_CHARACTER_SHEET_PRODUCT_SLUG,
  SESSION_ADDON_SESSION_ZERO_PRODUCT_SLUG,
  SESSION_ADDON_NEW_CAMPAIGN_PRODUCT_SLUG,
  SESSION_ADDON_THEMATIC_PROPS_PRODUCT_SLUG,
  SESSION_ADDON_EXTRA_HOUR_PRODUCT_SLUG,
  SESSION_ADDON_HYBRID_SERVICE_PRODUCT_SLUG,
  SESSION_ADDON_SCENARIO_CUSTOMIZATION_PRODUCT_SLUG,
  SESSION_CUSTOM_ADDITIONAL_SERVICE_PRODUCT_SLUG,
] as const;

export const SESSION_ENTITLEMENT_PRODUCT_SLUGS = [
  SESSION_PACKAGE_3_SESSIONS_PRODUCT_SLUG,
  SESSION_PACKAGE_5_SESSIONS_PRODUCT_SLUG,
  SESSION_SUBSCRIPTION_2_SESSIONS_MONTH_PRODUCT_SLUG,
  SESSION_SUBSCRIPTION_4_SESSIONS_MONTH_PRODUCT_SLUG,
] as const;

export const SESSION_RESERVATION_BASE_PRODUCT_SLUGS = [
  ...SESSION_BASE_PRODUCT_SLUGS,
  SESSION_CUSTOM_ADDITIONAL_SERVICE_PRODUCT_SLUG,
] as const;

export const SESSION_BOOKING_PRODUCT_SLUGS = [
  ...SESSION_BASE_PRODUCT_SLUGS,
  ...SESSION_ADDON_PRODUCT_SLUGS,
] as const;

export type SessionBaseProductSlug =
  (typeof SESSION_BASE_PRODUCT_SLUGS)[number];

export type SessionEntitlementProductSlug =
  (typeof SESSION_ENTITLEMENT_PRODUCT_SLUGS)[number];

export type SessionReservationBaseProductSlug =
  (typeof SESSION_RESERVATION_BASE_PRODUCT_SLUGS)[number];

export type SessionAddonProductSlug =
  (typeof SESSION_ADDON_PRODUCT_SLUGS)[number];

export type SessionBookingProductSlug =
  (typeof SESSION_BOOKING_PRODUCT_SLUGS)[number];
