import {
  SESSION_RESERVATION_BLOCKING_STATUSES,
  SESSION_RESERVATION_STATUSES,
} from '../types/session-reservation-status';
import { SESSION_BOOKING_MODES } from '../types/session-booking-mode';
import {
  SESSION_ADDON_CHARACTER_SHEET_PRODUCT_SLUG,
  SESSION_ADDON_EXTRA_HOUR_PRODUCT_SLUG,
  SESSION_ADDON_HYBRID_SERVICE_PRODUCT_SLUG,
  SESSION_ADDON_NEW_CAMPAIGN_PRODUCT_SLUG,
  SESSION_ADDON_PRODUCT_SLUGS,
  SESSION_ADDON_SCENARIO_CUSTOMIZATION_PRODUCT_SLUG,
  SESSION_ADDON_THEMATIC_PROPS_PRODUCT_SLUG,
  SESSION_BASE_PRODUCT_SLUGS,
  SESSION_BOOKING_PRODUCT_SLUGS,
  SESSION_CUSTOM_ADDITIONAL_SERVICE_PRODUCT_SLUG,
  SESSION_RESERVATION_BASE_PRODUCT_SLUGS,
  SESSION_SINGLE_SESSION_PRODUCT_SLUG,
} from '../types/session-booking-product';
import { SESSION_PRICE_STATUSES } from '../types/session-price-status';
import { SESSION_RESERVATION_SOURCE_KINDS } from '../types/session-reservation-source-kind';

export const SESSION_RESERVATION_CONFIG = {
  durationOptionsHours: [4, 5, 6, 7, 8],
  defaultDurationHours: 4,
  minLeadTimeHours: 24,
  bookingHorizonDays: 60,
  slotStepMinutes: 60,
  publicCreatedStatus: SESSION_RESERVATION_STATUSES.Pending,
  defaultBookingMode: SESSION_BOOKING_MODES.SingleSession,
  defaultSourceKind: SESSION_RESERVATION_SOURCE_KINDS.SystemOnly,
  defaultPriceStatus: SESSION_PRICE_STATUSES.Fixed,
  currency: 'PLN',
  baseProductSlugs: SESSION_BASE_PRODUCT_SLUGS,
  reservationBaseProductSlugs: SESSION_RESERVATION_BASE_PRODUCT_SLUGS,
  addonProductSlugs: SESSION_ADDON_PRODUCT_SLUGS,
  productSlugs: SESSION_BOOKING_PRODUCT_SLUGS,
  defaultBaseProductSlug: SESSION_SINGLE_SESSION_PRODUCT_SLUG,
  manualQuoteProductSlugs: [
    SESSION_ADDON_THEMATIC_PROPS_PRODUCT_SLUG,
    SESSION_CUSTOM_ADDITIONAL_SERVICE_PRODUCT_SLUG,
  ],
  addonProductSlugsRequiringCustomerDetails: [
    SESSION_ADDON_NEW_CAMPAIGN_PRODUCT_SLUG,
    SESSION_ADDON_THEMATIC_PROPS_PRODUCT_SLUG,
    SESSION_ADDON_SCENARIO_CUSTOMIZATION_PRODUCT_SLUG,
    SESSION_CUSTOM_ADDITIONAL_SERVICE_PRODUCT_SLUG,
  ],
  addonProductSlugsRequiringQuantity: [
    SESSION_ADDON_CHARACTER_SHEET_PRODUCT_SLUG,
    SESSION_ADDON_EXTRA_HOUR_PRODUCT_SLUG,
  ],
  addonProductSlugsWithPercentagePricing: [
    SESSION_ADDON_HYBRID_SERVICE_PRODUCT_SLUG,
  ],
  blockingReservationStatuses: SESSION_RESERVATION_BLOCKING_STATUSES,
} as const;
