export const STAFFING_REALIZATION_RPC = {
  getAdminList: 'get_admin_staffing_realization_list',
  validateAdmin: 'validate_admin_staffing_realization',
  openAdmin: 'open_admin_staffing_realization',
  deleteAdmin: 'delete_admin_staffing_realization',
  archiveAdmin: 'archive_admin_staffing_realization',
  getAdminRecruitmentPolicy: 'get_admin_staffing_recruitment_policy',
  saveAdminRecruitmentPolicy: 'save_admin_staffing_recruitment_policy',
  createAdmin: 'create_admin_staffing_realization',
  updateAdminCore: 'update_admin_staffing_realization',
  getAdminDetail: 'get_admin_staffing_realization_detail',
  getAdminSchedule: 'get_admin_staffing_realization_schedule',
  saveAdminSchedule: 'save_admin_staffing_realization_schedule',
  getAdminTravelTerms: 'get_admin_staffing_realization_travel_terms',
  saveAdminTravelTerms: 'save_admin_staffing_realization_travel_terms',
} as const;
